export const DONATION_REQUEST_SUCCESS="DONATION_REQUEST_SUCCESS"
export const DONATION_REQUEST ="DONATION_REQUEST"
export const DONATION_REQUEST_FAILURE="DONATION_REQUEST_FAILURE"
export const DONATED ="DONATED"
